### ISSUE TITLE
Initialising problem with other mods

### ISSUE THREAD

**Issue by ScarletX8** [doch2/SmartMovingReboot#15]
I recently download smart moving mod and when I tried to play it with dynamic stealth mod and epic fight mod

**Comment by doch2** [comment]
I think the comments got cut off. Please write down the next content.

**Comment by ScarletX8** [comment]
I recently download smart moving mod and when I tried to Play it with dynamic stealth mode, epic fight mod and other adventuring mod the game crash

**Comment by ScarletX8** [comment]
[Uploading crash-2021-09-19_15.54.03-client.txt…]()

**Comment by ScarletX8** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/19/21 3:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Smart Moving (smartmoving)
Caused by: java.lang.NoClassDefFoundError: net/smart/render/SRInfo
	at net.smart.moving.SMMod.register(SMMod.java:95)
	at net.smart.moving.SMMod.preInit(SMMod.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.smart.render.SRInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 36958424 bytes (35 MB) / 364068864 bytes (347 MB) up to 3826515968 bytes (3649 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx3662M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version         | Source                              | Signature                                |
	|:----- |:----------------- |:--------------- |:----------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2          | minecraft.jar                       | None                                     |
	| LCH   | mcp               | 9.42            | minecraft.jar                       | None                                     |
	| LCH   | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2855.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2855    | forge-1.12.2-14.23.5.2855.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | alcatrazcore      | 1.0.4           | alcatrazcore-1.0.4.jar              | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | collective        | 2.64            | collective-1.12.2-2.64.jar          | None                                     |
	| LCH   | disenchanter      | 1.7             | disenchanter-[1.12]1.7.jar          | None                                     |
	| LCH   | fantasticlib      | 1.12.2.047      | FantasticLib-1.12.2.047.jar         | None                                     |
	| LCH   | dynamicstealth    | 1.12.2.114      | DynamicStealth-1.12.2.114.jar       | None                                     |
	| LCH   | epicfight         | 1.12.2-2.2.7    | EpicFightMod-1.12.2-2.2.7.jar       | None                                     |
	| LCH   | llibrary          | 1.7.20          | llibrary-1.7.20-1.12.2.jar          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire        | 1.9.1           | iceandfire-1.9.1-1.12.2.jar         | None                                     |
	| LCH   | mahoutsukai       | 1.12.2-v1.19.49 | mahoutsukai-1.12.2-v1.19.49.jar     | None                                     |
	| LCH   | medieval_craft    | 1.14.4          | MedievalCraft-1.12.2-1.15.11.jar    | None                                     |
	| LCH   | notreepunching    | 2.0.21          | notreepunching-2.0.21.jar           | None                                     |
	| LCE   | smartmoving       | 1.12.2-17.0-RC4 | SmartMoving-1.12.2-17.0-RC4.jar     | None                                     |
	| LC    | starterkit        | 2.4             | starterkit_1.12.2-2.4.jar           | None                                     |
	| LC    | travelersbackpack | 1.0.35          | TravelersBackpack-1.12.2-1.0.35.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 510'
	No Tree Punching: You are not running an official build. This version will NOT be supported by the author.
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 510
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by ScarletX8** [comment]
> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
> llibrary (llibrary-core-1.0.11-1.12.2.jar)
> iceandfire (iceandfire-1.9.1-1.12.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Shall we play a game?
> 
> Time: 9/19/21 3:54 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Smart Moving (smartmoving)
> Caused by: java.lang.NoClassDefFoundError: net/smart/render/SRInfo
> at net.smart.moving.SMMod.register(SMMod.java:95)
> at net.smart.moving.SMMod.preInit(SMMod.java:63)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
> at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
> at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
> at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
> at net.minecraft.client.main.Main.main(SourceFile:123)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: net.smart.render.SRInfo
> at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 42 more
> Caused by: java.lang.NullPointerException
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- System Details --
> Details:
> Minecraft Version: 1.12.2
> Operating System: Windows 10 (amd64) version 10.0
> Java Version: 1.8.0_51, Oracle Corporation
> Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> Memory: 36958424 bytes (35 MB) / 364068864 bytes (347 MB) up to 3826515968 bytes (3649 MB)
> JVM Flags: 3 total; -Xmn128M -Xmx3662M -XX:+UseConcMarkSweepGC
> IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 18 mods loaded, 18 mods active
> States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> ```
> | State | ID                | Version         | Source                              | Signature                                |
> |:----- |:----------------- |:--------------- |:----------------------------------- |:---------------------------------------- |
> | LCH   | minecraft         | 1.12.2          | minecraft.jar                       | None                                     |
> | LCH   | mcp               | 9.42            | minecraft.jar                       | None                                     |
> | LCH   | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2855.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> | LCH   | forge             | 14.23.5.2855    | forge-1.12.2-14.23.5.2855.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> | LCH   | alcatrazcore      | 1.0.4           | alcatrazcore-1.0.4.jar              | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
> | LCH   | collective        | 2.64            | collective-1.12.2-2.64.jar          | None                                     |
> | LCH   | disenchanter      | 1.7             | disenchanter-[1.12]1.7.jar          | None                                     |
> | LCH   | fantasticlib      | 1.12.2.047      | FantasticLib-1.12.2.047.jar         | None                                     |
> | LCH   | dynamicstealth    | 1.12.2.114      | DynamicStealth-1.12.2.114.jar       | None                                     |
> | LCH   | epicfight         | 1.12.2-2.2.7    | EpicFightMod-1.12.2-2.2.7.jar       | None                                     |
> | LCH   | llibrary          | 1.7.20          | llibrary-1.7.20-1.12.2.jar          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
> | LCH   | iceandfire        | 1.9.1           | iceandfire-1.9.1-1.12.2.jar         | None                                     |
> | LCH   | mahoutsukai       | 1.12.2-v1.19.49 | mahoutsukai-1.12.2-v1.19.49.jar     | None                                     |
> | LCH   | medieval_craft    | 1.14.4          | MedievalCraft-1.12.2-1.15.11.jar    | None                                     |
> | LCH   | notreepunching    | 2.0.21          | notreepunching-2.0.21.jar           | None                                     |
> | LCE   | smartmoving       | 1.12.2-17.0-RC4 | SmartMoving-1.12.2-17.0-RC4.jar     | None                                     |
> | LC    | starterkit        | 2.4             | starterkit_1.12.2-2.4.jar           | None                                     |
> | LC    | travelersbackpack | 1.0.35          | TravelersBackpack-1.12.2-1.0.35.jar | None                                     |
> 
> Loaded coremods (and transformers): 
> ```
> 
> llibrary (llibrary-core-1.0.11-1.12.2.jar)
> net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
> net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
> iceandfire (iceandfire-1.9.1-1.12.2.jar)
> com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
> GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 510'
> No Tree Punching: You are not running an official build. This version will NOT be supported by the author.
> OptiFine Version: OptiFine_1.12.2_HD_U_G5
> OptiFine Build: 20210124-142939
> Render Distance Chunks: 3
> Mipmaps: 4
> Anisotropic Filtering: 1
> Antialiasing: 0
> Multitexture: false
> Shaders: null
> OpenGlVersion: 4.4.0 - Build 21.20.16.4550
> OpenGlRenderer: Intel(R) HD Graphics 510
> OpenGlVendor: Intel
> CpuCount: 4

It is my game crash report

**Comment by ScarletX8** [comment]
It is my game crash report

**Comment by ScarletX8** [comment]
I recently download smart moving mod and I tried to install it with dynamic
stealth mod, epic fight mod and other adventuring mod this Is my game crash
report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/19/21 3:54 PM
Description: There was a severe problem during mod loading that has caused
the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception
from Smart Moving (smartmoving)
Caused by: java.lang.NoClassDefFoundError: net/smart/render/SRInfo
at net.smart.moving.SMMod.register(SMMod.java:95)
at net.smart.moving.SMMod.preInit(SMMod.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at
com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at
com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at
com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at
net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
at
net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at
com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at
com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at
com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at
net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
at
net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.smart.render.SRInfo
at
net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 42 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 36958424 bytes (35 MB) / 364068864 bytes (347 MB) up to 3826515968
bytes (3649 MB)
JVM Flags: 3 total; -Xmn128M -Xmx3662M -XX:+UseConcMarkSweepGC
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine
OptiFine_1.12.2_HD_U_G5 18 mods loaded, 18 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized
'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E'
= Errored

| State | ID                | Version         | Source
        | Signature                                |
|:----- |:----------------- |:---------------
|:-----------------------------------
|:---------------------------------------- |
| LCH   | minecraft         | 1.12.2          | minecraft.jar
         | None                                     |
| LCH   | mcp               | 9.42            | minecraft.jar
         | None                                     |
| LCH   | FML               | 8.0.99.99       |
forge-1.12.2-14.23.5.2855.jar       |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCH   | forge             | 14.23.5.2855    |
forge-1.12.2-14.23.5.2855.jar       |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCH   | alcatrazcore      | 1.0.4           | alcatrazcore-1.0.4.jar
        | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
| LCH   | collective        | 2.64            | collective-1.12.2-2.64.jar
        | None                                     |
| LCH   | disenchanter      | 1.7             | disenchanter-[1.12]1.7.jar
        | None                                     |
| LCH   | fantasticlib      | 1.12.2.047      |
FantasticLib-1.12.2.047.jar         | None
   |
| LCH   | dynamicstealth    | 1.12.2.114      |
DynamicStealth-1.12.2.114.jar       | None
   |
| LCH   | epicfight         | 1.12.2-2.2.7    |
EpicFightMod-1.12.2-2.2.7.jar       | None
   |
| LCH   | llibrary          | 1.7.20          | llibrary-1.7.20-1.12.2.jar
        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
| LCH   | iceandfire        | 1.9.1           |
iceandfire-1.9.1-1.12.2.jar         | None
   |
| LCH   | mahoutsukai       | 1.12.2-v1.19.49 |
mahoutsukai-1.12.2-v1.19.49.jar     | None
   |
| LCH   | medieval_craft    | 1.14.4          |
MedievalCraft-1.12.2-1.15.11.jar    | None
   |
| LCH   | notreepunching    | 2.0.21          | notreepunching-2.0.21.jar
         | None                                     |
| LCE   | smartmoving       | 1.12.2-17.0-RC4 |
SmartMoving-1.12.2-17.0-RC4.jar     | None
   |
| LC    | starterkit        | 2.4             | starterkit_1.12.2-2.4.jar
         | None                                     |
| LC    | travelersbackpack | 1.0.35          |
TravelersBackpack-1.12.2-1.0.35.jar | None
   |

Loaded coremods (and transformers):
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer:
'Intel(R) HD Graphics 510'
No Tree Punching: You are not running an official build. This version will
NOT be supported by the author.
OptiFine Version: OptiFine_1.12.2_HD_U_G5
OptiFine Build: 20210124-142939
Render Distance Chunks: 3
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.4.0 - Build 21.20.16.4550
OpenGlRenderer: Intel(R) HD Graphics 510
OpenGlVendor: Intel
CpuCount: 4
